[2024-06-11 14:45:57,292] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.7:5000 - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:45:57,295] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,464] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,593] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,605] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,606] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,743] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:00,747] INFO _log() L97   192.168.1.7 - - [11/Jun/2024 14:46:00] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 14:46:35,526] ERROR log_exception() L838  Exception on /new_entry_id [GET] - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\my_dayling_entry_api\app.py", line 71, in new_entry_id
    new_entry_id = entry_db_session.get_next_entry_id()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\my_dayling_entry_api\database\database.py", line 125, in get_next_entry_id
    last_entry_id = query_result.entryID
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'entryID'
[2024-06-11 14:46:35,529] INFO _log() L97   127.0.0.1 - - [11/Jun/2024 14:46:35] "[35m[1mGET /new_entry_id HTTP/1.1[0m" 500 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:07:55,862] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.7:5000 - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:07:55,863] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:08:11,444] ERROR log_exception() L838  Exception on /new_entry_id [GET] - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\my_dayling_entry_api\app.py", line 71, in new_entry_id
    new_entry_id = entry_db_session.get_next_entry_id()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\my_dayling_entry_api\database\database.py", line 143, in get_next_entry_id
    print('Database is emppty: ' + self.is_database_empty)
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "bool") to str
[2024-06-11 15:08:11,446] INFO _log() L97   127.0.0.1 - - [11/Jun/2024 15:08:11] "[35m[1mGET /new_entry_id HTTP/1.1[0m" 500 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:08:42,181] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.7:5000 - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:08:42,184] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:08:44,382] INFO _log() L97   127.0.0.1 - - [11/Jun/2024 15:08:44] "GET /new_entry_id HTTP/1.1" 200 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:10:10,511] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.7:5000 - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:10:10,513] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:10:13,226] INFO _log() L97   127.0.0.1 - - [11/Jun/2024 15:10:13] "GET /new_entry_id HTTP/1.1" 200 - - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-06-11 15:19:26,490] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.7:5000 - call_trace=C:\Users\adilson\Documents\Programming\Python\FlaskProjects\MyDaylingEntry\venv\Lib\site-packages\werkzeug\_internal.py L97  
